# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'digitalagentapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for digitalagentapp
  pod 'Firebase/Core', '~> 5.15.0'
  target 'digitalagentappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'digitalagentapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for digitalagentapp-tvOS

  target 'digitalagentapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end